CREATE TABLE veiculos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    placa VARCHAR(10) NOT NULL UNIQUE,
    ano INTEGER NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT pk_veiculos 
	PRIMARY KEY (id)
);

SELECT * FROM veiculos;

INSERT INTO veiculos (marca, modelo, placa, ano, tipo, status)
	VALUES
    	('Ford', 'Ranger', 'ABC-1234', 2024, 'Picape', 'Operacional'),
    	('Fiat', 'Ducato', 'DEF-5678', 2023, 'Van', 'Em manutenção'),
    	('Toyota', 'Corolla', 'GHI-9012', 2022, 'Sedan', 'Operacional'),
        ('Mercedes-Benz', 'Sprinter', 'JKL-3456', 2021, 'Utilitário', 'Inativo');