CREATE TABLE veiculos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    placa VARCHAR(10) NOT NULL UNIQUE,
    ano INTEGER NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT pk_veiculos 
	PRIMARY KEY (id)
);

INSERT INTO veiculos (marca, modelo, placa, ano, tipo, status)
	VALUES
    	('Ford', 'Ranger', 'ABC-1234', 2024, 'Picape', 'Operacional'),
    	('Fiat', 'Ducato', 'DEF-5678', 2023, 'Van', 'Em manutenção'),
    	('Toyota', 'Corolla', 'GHI-9012', 2022, 'Sedan', 'Operacional'),
        ('Mercedes-Benz', 'Sprinter', 'JKL-3456', 2021, 'Utilitário', 'Inativo');

CREATE TABLE motoristas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    cnh VARCHAR(11) NOT NULL,
    categoria_cnh VARCHAR(2) NOT NULL,
    validade_cnh DATE NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    status VARCHAR(10) NOT NULL,

    CONSTRAINT pk_motoristas 
		PRIMARY KEY (id),
		
    CONSTRAINT uq_motoristas_cpf 
		UNIQUE (cpf),
		
    CONSTRAINT uq_motoristas_cnh 
		UNIQUE (cnh),
		
    CONSTRAINT ck_motoristas_categoria 
		CHECK (categoria_cnh IN ('A', 'B', 'AB', 'C', 'D', 'E')),
		
    CONSTRAINT ck_motoristas_status 
		CHECK (status IN ('Ativo', 'Inativo'))
);

CREATE TABLE manutencoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    veiculo_id INTEGER NOT NULL,
    oficina VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    custo NUMERIC(10,2),
    status VARCHAR(20) NOT NULL,

    CONSTRAINT pk_manutencoes 
		PRIMARY KEY (id),
		
    CONSTRAINT fk_manutencoes_veiculo
        FOREIGN KEY (veiculo_id)
        REFERENCES veiculos(id),
		
    CONSTRAINT ck_manutencoes_tipo
        CHECK (tipo IN ('Preventiva', 'Corretiva')),
		
    CONSTRAINT ck_manutencoes_status
        CHECK (status IN ('Em andamento', 'Concluída', 'Cancelada'))
);

CREATE TABLE documentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    veiculo_id INTEGER NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    numero VARCHAR(50),
    data_emissao DATE NOT NULL,
    data_validade DATE NOT NULL,
    arquivo VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT pk_documentos 
		PRIMARY KEY (id),
		
    CONSTRAINT fk_documentos_veiculo
        FOREIGN KEY (veiculo_id)
        REFERENCES veiculos(id),
		
    CONSTRAINT ck_documentos_tipo
        CHECK (tipo IN ('CRLV', 'Seguro', 'Licenciamento', 'Outros')),
		
    CONSTRAINT ck_documentos_status
        CHECK (status IN ('Válido', 'Vencido', 'Pendente'))
);